name: Tailscale

on:  
  workflow_dispatch:  

jobs:  
  setup-windows-vm:  
    runs-on: windows-latest  

    steps:  
      - name: Download and install Tailscale  
        run: |  
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-1.66.2.exe" -OutFile "tailscale.exe"  
          Start-Process -FilePath "tailscale.exe" -ArgumentList "/quiet" -NoNewWindow -Wait  

      - name: Start Tailscale and get login URL  
        run: |  
          tailscale up --qr >> tailscale_url.txt  
          Get-Content tailscale_url.txt  

      - name: Output login link  
        run: Get-Content tailscale_url.txt
